;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        counsel-M-x
        downcase-region
        end-of-buffer
        eval-last-sexp
        fill-paragraph
        kill-region
        org-beginning-of-line
        org-cycle
        org-end-of-line
        org-force-self-insert
        org-kill-line
        org-meta-return
        org-open-line
        org-return
        org-self-insert-command
        org-shiftleft
        org-yank
        paredit-forward-delete
        paredit-forward-slurp-sexp
        paredit-kill
        paredit-open-round
        paredit-semicolon
        query-replace
        sp-delete-char
        sp-kill-region
        ))

(setq mc/cmds-to-run-once
      '(
        ))
